---
# 云原生DevOps平台完整部署脚本
# 基于OpenStack和Kubernetes的云原生DevOps平台

- name: 部署云原生DevOps平台
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    # 部署配置
    deployment_mode: "full"  # full, minimal, custom
    skip_verification: false
    
    # 系统配置
    timezone: "Asia/Shanghai"
    ntp_servers:
      - "ntp.aliyun.com"
      - "time.windows.com"
    
    # 网络配置
    cluster_network: "192.168.1.0/24"
    service_network: "10.96.0.0/12"
    pod_network: "10.244.0.0/16"
    
    # 应用配置
    app_namespace: "production"
    app_name: "web-app"
    app_replicas: 3
    app_domain: "app.example.com"

  tasks:
    # 1. 基础环境配置
    - name: 配置基础环境
      include: playbooks/01-common-setup.yml
      tags: [setup, common]

    # 2. Docker安装配置
    - name: 安装Docker
      include: playbooks/02-docker-setup.yml
      tags: [setup, docker]

    # 3. Kubernetes集群部署
    - name: 部署Kubernetes集群
      include: playbooks/03-kubernetes-fixed.yml
      tags: [setup, kubernetes]

    # 4. 监控系统部署
    - name: 部署监控系统
      include: playbooks/04-monitoring-setup.yml
      tags: [setup, monitoring]
      when: deployment_mode in ['full', 'custom']

    # 5. CI/CD系统部署
    - name: 部署CI/CD系统
      include: playbooks/05-cicd-setup.yml
      tags: [setup, cicd]
      when: deployment_mode in ['full', 'custom']

    # 6. 应用部署
    - name: 部署示例应用
      include: playbooks/06-application-deploy.yml
      tags: [deploy, application]

    # 7. 系统验证
    - name: 验证系统部署
      include: playbooks/07-verification.yml
      tags: [verify, test]
      when: not skip_verification

  post_tasks:
    - name: 显示部署完成信息
      debug:
        msg:
          - "=== 云原生DevOps平台部署完成 ==="
          - "部署模式: {{ deployment_mode }}"
          - "部署时间: {{ ansible_date_time.iso8601 }}"
          - "控制节点: {{ groups['control_nodes'] | join(', ') }}"
          - "计算节点: {{ groups['compute_nodes'] | join(', ') }}"
          - "监控节点: {{ groups['monitoring_nodes'] | join(', ') }}"
          - "CI/CD节点: {{ groups['cicd_nodes'] | join(', ') }}"
          - ""
          - "=== 访问地址 ==="
          - "应用地址: http://{{ app_domain }}"
          - "监控地址: http://{{ ansible_default_ipv4.address }}:{{ prometheus_port }}"
          - "仪表板: http://{{ ansible_default_ipv4.address }}:{{ grafana_port }}"
          - "GitLab: http://{{ ansible_default_ipv4.address }}:{{ gitlab_port }}"
          - "Jenkins: http://{{ ansible_default_ipv4.address }}:{{ jenkins_port }}"
          - "Harbor: http://{{ ansible_default_ipv4.address }}:{{ harbor_port }}"
          - ""
          - "=== 下一步操作 ==="
          - "1. 访问应用验证部署"
          - "2. 配置监控告警规则"
          - "3. 设置CI/CD流水线"
          - "4. 配置SSL证书"
          - "5. 备份重要数据"
