---
# 云原生DevOps平台服务器清单
all:
  children:
    # 控制节点组
    control_nodes:
      hosts:
        control-01:
          ansible_host: 192.168.76.141
          ansible_user: root
          node_role: control
          k8s_role: master
      vars:
        # 控制节点通用变量
        openstack_services:
          - keystone
          - glance
          - nova-api
          - neutron-server
          - cinder-api
        k8s_control_plane: true

    # 计算节点组
    compute_nodes:
      hosts:
        compute-01:
          ansible_host: 192.168.76.141
          ansible_user: root
          node_role: compute
          k8s_role: worker
      vars:
        # 计算节点通用变量
        openstack_services:
          - nova-compute
          - neutron-agent
        k8s_worker: true

    # 存储节点组
    storage_nodes:
      hosts:
        storage-01:
          ansible_host: 192.168.76.141
          ansible_user: root
          node_role: storage
      vars:
        # 存储节点通用变量
        openstack_services:
          - cinder-volume
          - swift-storage

    # 监控节点组
    monitoring_nodes:
      hosts:
        monitor-01:
          ansible_host: 192.168.76.141
          ansible_user: root
          node_role: monitoring
      vars:
        # 监控服务
        monitoring_services:
          - prometheus
          - grafana
          - alertmanager
          - node-exporter

    # CI/CD节点组
    cicd_nodes:
      hosts:
        cicd-01:
          ansible_host: 192.168.76.141
          ansible_user: root
          node_role: cicd
      vars:
        # CI/CD服务
        cicd_services:
          - gitlab
          - jenkins
          - registry

  # 全局变量
  vars:
    # 网络配置
    cluster_network: "192.168.76.0/24"
    service_network: "10.96.0.0/12"
    pod_network: "10.244.0.0/16"
    
    # Kubernetes配置
    kubernetes_version: "1.28.0"
    containerd_version: "1.7.0"
    cni_version: "1.3.0"
    
    # 镜像仓库配置
    registry_url: "registry.example.com"
    registry_port: 5000
    
    # 监控配置
    prometheus_port: 9090
    grafana_port: 3000
    alertmanager_port: 9093
    
    # 应用配置
    app_namespace: "production"
    app_replicas: 3
    
    # 安全配置
    enable_tls: true
    cert_manager_version: "v1.13.0"
    
    # 存储配置
    storage_class: "fast-ssd"
    storage_size: "100Gi"
